### ISSUE TITLE
Remove "completed execution" from end of logs

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/ai4earth-serengeti-runtime#3]
In cases where there's an issue with the submission, having "Completed execution" at the end of the log is misleading.

<img width="887" alt="Screenshot 2019-11-15 11 12 15" src="https://user-images.githubusercontent.com/22667367/68969632-4ad43280-079a-11ea-832f-7d33bcba2418.png">

**Comment by pjbull** [comment]
String updated in 4465495fbad3dc2258debd864df5e47a9bd3c279
